context:
  name: apache-airflow-providers-opensearch
  version: "1.13.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_opensearch-${{ version }}.tar.gz
  sha256: e2d5a3017badf61e62c8f05ac3d480a83d619b2d2002ad6aa785f7cbd3663d7f

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==4.0.2
  run:
    - python >=${{ python_min }}
    - apache-airflow >=3.0.0
    - apache-airflow-providers-common-compat >=1.12.0
    - opensearch-py >=2.2.0

tests:
  - python:
      imports:
        - airflow.providers.opensearch
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-opensearch for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-opensearch/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
